import { Priority, ODLStatus, SyncStatus } from '@prisma/client'
import { Part } from './Part'

export interface ODLEntity {
  id: string
  odlNumber: string
  partId: string
  quantity: number
  priority: Priority
  status: ODLStatus
  qrCode: string
  createdAt: Date
  updatedAt: Date
  
  // Gamma MES sync tracking
  gammaId?: string | null
  lastSyncAt?: Date | null
  syncStatus: SyncStatus
  
  
  // Relations
  part?: Part
}

export class ODL implements ODLEntity {
  public readonly id: string
  public readonly odlNumber: string
  public readonly partId: string
  public quantity: number
  public priority: Priority
  public status: ODLStatus
  public readonly qrCode: string
  public readonly createdAt: Date
  public updatedAt: Date
  
  // Gamma MES sync tracking
  public gammaId?: string | null
  public lastSyncAt?: Date | null
  public syncStatus: SyncStatus
  
  
  
  // Relations
  public part?: Part

  constructor(data: ODLEntity) {
    this.id = data.id
    this.odlNumber = data.odlNumber
    this.partId = data.partId
    this.quantity = data.quantity
    this.priority = data.priority
    this.status = data.status
    this.qrCode = data.qrCode
    this.createdAt = data.createdAt
    this.updatedAt = data.updatedAt
    this.gammaId = data.gammaId
    this.lastSyncAt = data.lastSyncAt
    this.syncStatus = data.syncStatus
    this.part = data.part
  }

  // Business methods
  public updateQuantity(newQuantity: number): void {
    if (newQuantity < 1) {
      throw new Error('Quantity must be at least 1')
    }
    this.quantity = newQuantity
    this.markAsUpdated()
  }

  public setPriority(priority: Priority): void {
    this.priority = priority
    this.markAsUpdated()
  }

  public startCleanRoom(): void {
    if (this.status !== ODLStatus.CREATED) {
      throw new Error(`Cannot start clean room for ODL with status ${this.status}`)
    }
    this.status = ODLStatus.IN_CLEANROOM
    this.markAsUpdated()
  }

  public completeCleanRoom(): void {
    if (this.status !== ODLStatus.IN_CLEANROOM) {
      throw new Error(`Cannot complete clean room for ODL with status ${this.status}`)
    }
    this.status = ODLStatus.CLEANROOM_COMPLETED
    this.markAsUpdated()
  }

  public startAutoclave(): void {
    if (this.status !== ODLStatus.CLEANROOM_COMPLETED) {
      throw new Error(`Cannot start autoclave for ODL with status ${this.status}`)
    }
    this.status = ODLStatus.IN_AUTOCLAVE
    this.markAsUpdated()
  }

  public completeAutoclave(): void {
    if (this.status !== ODLStatus.IN_AUTOCLAVE) {
      throw new Error(`Cannot complete autoclave for ODL with status ${this.status}`)
    }
    this.status = ODLStatus.AUTOCLAVE_COMPLETED
    this.markAsUpdated()
  }

  public hold(): void {
    if (this.status === ODLStatus.COMPLETED || this.status === ODLStatus.CANCELLED) {
      throw new Error(`Cannot hold ODL with status ${this.status}`)
    }
    this.status = ODLStatus.ON_HOLD
    this.markAsUpdated()
  }

  public cancel(): void {
    if (this.status === ODLStatus.COMPLETED) {
      throw new Error('Cannot cancel completed ODL')
    }
    this.status = ODLStatus.CANCELLED
    this.markAsUpdated()
  }

  public complete(): void {
    this.status = ODLStatus.COMPLETED
    this.markAsUpdated()
  }


  public markAsSynced(gammaId?: string): void {
    this.lastSyncAt = new Date()
    this.syncStatus = SyncStatus.SUCCESS
    if (gammaId) {
      this.gammaId = gammaId
    }
    this.markAsUpdated()
  }

  public markSyncFailed(): void {
    this.syncStatus = SyncStatus.FAILED
    this.markAsUpdated()
  }

  // Getters for effective values (considering part defaults)
  public get partNumber(): string {
    return this.part?.partNumber || ''
  }

  public get description(): string {
    return this.part?.description || ''
  }

  public isInProduction(): boolean {
    return [
      ODLStatus.IN_CLEANROOM,
      ODLStatus.CLEANROOM_COMPLETED,
      ODLStatus.IN_AUTOCLAVE,
      ODLStatus.AUTOCLAVE_COMPLETED,
      ODLStatus.IN_NDI,
    ].includes(this.status as any) // eslint-disable-line @typescript-eslint/no-explicit-any
  }

  public isCompleted(): boolean {
    return this.status === ODLStatus.COMPLETED
  }

  public isFromGamma(): boolean {
    return !!this.gammaId
  }

  private markAsUpdated(): void {
    this.updatedAt = new Date()
  }

  // Static factory methods
  static create(data: Omit<ODLEntity, 'id' | 'createdAt' | 'updatedAt' | 'qrCode' | 'status'>): ODL {
    const now = new Date()
    return new ODL({
      id: '', // Will be set by repository
      createdAt: now,
      updatedAt: now,
      qrCode: '', // Will be generated by repository
      status: ODLStatus.CREATED,
      ...data,
      syncStatus: SyncStatus.SUCCESS,
    })
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  static fromPrisma(data: any): ODL { // TODO: Replace with proper Prisma type
    return new ODL({
      ...data,
      part: data.part ? Part.fromPrisma(data.part) : undefined,
    })
  }
}