#!/bin/bash

echo "🔧 Script di accesso al database Netlify"
echo "========================================"
echo ""
echo "Per accedere al database Netlify:"
echo ""
echo "1. Vai su https://app.netlify.com"
echo "2. Seleziona il tuo sito: manta-management-system"
echo "3. Vai su: Site configuration > Environment variables"
echo "4. Copia il valore di DATABASE_URL"
echo ""
echo "5. Poi esegui uno dei seguenti comandi:"
echo ""
echo "   # Per Prisma Studio (interfaccia grafica):"
echo "   DATABASE_URL='incolla-qui-il-database-url' npx prisma studio"
echo ""
echo "   # Per accesso diretto con psql:"
echo "   psql 'incolla-qui-il-database-url'"
echo ""
echo "   # Per reset completo del database:"
echo "   DATABASE_URL='incolla-qui-il-database-url' npx prisma db push --force-reset"
echo ""
echo "   # Per seed del database dopo reset:"
echo "   DATABASE_URL='incolla-qui-il-database-url' npx prisma db seed"
echo ""
echo "⚠️  ATTENZIONE: Il reset eliminerà TUTTI i dati!"
echo ""
echo "📝 Note:"
echo "- Prisma Studio si aprirà su http://localhost:5555"
echo "- Puoi navigare e modificare i dati direttamente"
echo "- Per eliminare tutti i record di una tabella in Prisma Studio:"
echo "  1. Seleziona la tabella"
echo "  2. Seleziona tutti i record (Ctrl+A)"
echo "  3. Clicca Delete"
echo ""